const products = [
    {
        productId: 1,
        productName: "Product 1",
        productPrice: 19.99,
        category: 1,
        brand: 2,
        averageRating: 4,
        totalRating: 100,
        productImage:
          "https://dosi-in.com/file/detailed/487/dosiin-downtown-ao-local-brand-chinh-hang-graffiti-downtown-tee-487675487675.jpg?w=1000&h=1000&fit=fill&fm=webp",
        saleType: "percentage",
        saleValue: 15,
      },
    {
        productId: 2,
        productName: "Product 1",
        productPrice: 19.99,
        category: 1,
        brand: 2,
        averageRating: 4,
        totalRating: 100,
        productImage:
          "https://dosi-in.com/file/detailed/487/dosiin-downtown-ao-local-brand-chinh-hang-graffiti-downtown-tee-487675487675.jpg?w=1000&h=1000&fit=fill&fm=webp",
        saleType: "percentage",
        saleValue: 15,
      },
    {
        productId: 3,
        productName: "Product 1",
        productPrice: 19.99,
        category: 1,
        brand: 2,
        averageRating: 4,
        totalRating: 100,
        productImage:
          "https://dosi-in.com/file/detailed/487/dosiin-downtown-ao-local-brand-chinh-hang-graffiti-downtown-tee-487675487675.jpg?w=1000&h=1000&fit=fill&fm=webp",
        saleType: "percentage",
        saleValue: 15,
      },
    {
        productId: 4,
        productName: "Product 1",
        productPrice: 19.99,
        category: 1,
        brand: 2,
        averageRating: 4,
        totalRating: 100,
        productImage:
          "https://dosi-in.com/file/detailed/487/dosiin-downtown-ao-local-brand-chinh-hang-graffiti-downtown-tee-487675487675.jpg?w=1000&h=1000&fit=fill&fm=webp",
        saleType: "percentage",
        saleValue: 15,
      },
    {
        productId: 5,
        productName: "Product 1",
        productPrice: 19.99,
        category: 1,
        brand: 2,
        averageRating: 4,
        totalRating: 100,
        productImage:
          "https://dosi-in.com/file/detailed/487/dosiin-downtown-ao-local-brand-chinh-hang-graffiti-downtown-tee-487675487675.jpg?w=1000&h=1000&fit=fill&fm=webp",
        saleType: "percentage",
        saleValue: 15,
      },
    {
        productId: 6,
        productName: "Product 1",
        productPrice: 19.99,
        category: 1,
        brand: 2,
        averageRating: 4,
        totalRating: 100,
        productImage:
          "https://dosi-in.com/file/detailed/487/dosiin-downtown-ao-local-brand-chinh-hang-graffiti-downtown-tee-487675487675.jpg?w=1000&h=1000&fit=fill&fm=webp",
        saleType: "percentage",
        saleValue: 15,
      },
    {
        productId: 7,
        productName: "Product 1",
        productPrice: 19.99,
        category: 1,
        brand: 2,
        averageRating: 4,
        totalRating: 100,
        productImage:
          "https://dosi-in.com/file/detailed/487/dosiin-downtown-ao-local-brand-chinh-hang-graffiti-downtown-tee-487675487675.jpg?w=1000&h=1000&fit=fill&fm=webp",
        saleType: "percentage",
        saleValue: 15,
      },
    {
        productId: 8,
        productName: "Product 1",
        productPrice: 19.99,
        category: 1,
        brand: 2,
        averageRating: 4,
        totalRating: 100,
        productImage:
          "https://dosi-in.com/file/detailed/487/dosiin-downtown-ao-local-brand-chinh-hang-graffiti-downtown-tee-487675487675.jpg?w=1000&h=1000&fit=fill&fm=webp",
        saleType: "percentage",
        saleValue: 15,
      },
    {
        productId: 9,
        productName: "Product 1",
        productPrice: 19.99,
        category: 1,
        brand: 2,
        averageRating: 4,
        totalRating: 100,
        productImage:
          "https://dosi-in.com/file/detailed/487/dosiin-downtown-ao-local-brand-chinh-hang-graffiti-downtown-tee-487675487675.jpg?w=1000&h=1000&fit=fill&fm=webp",
        saleType: "percentage",
        saleValue: 15,
      },
    {
        productId: 10,
        productName: "Product 1",
        productPrice: 19.99,
        category: 1,
        brand: 2,
        averageRating: 4,
        totalRating: 100,
        productImage:
          "https://dosi-in.com/file/detailed/487/dosiin-downtown-ao-local-brand-chinh-hang-graffiti-downtown-tee-487675487675.jpg?w=1000&h=1000&fit=fill&fm=webp",
        saleType: "percentage",
        saleValue: 15,
      },
    
  ];

  export default products;